baseURL = "https://ismail.hassani.eu/"
languageCode = "en-us"
title = "Ismail Hassani"
theme = "codemaster"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "ismailhassani"

googleAnalytics = "UA-180668440-1"

[deployment]
    [[deployment.targets]]
        name = "Azure"
        URL = "azblob://$web"

[params]
    author = "Ismail Hassani"
    description = "Ismail Hassani's personal website"
    keywords = "blog,developer,personal,.Net,software,uno platform"
    info = "Full Stack .Net Developer"
    avatarurl = "images/avatar.jpg"
    gravatar = "ismail.hassani@i-synergy.nl"
    footercontent = "A place where I can share my vision and experiences ;)"

    dateformat = "January 2, 2006"

    hideFooter = false
    hideCredits = true
    hideCopyright = true
    since = 2020

    # Git Commit in Footer, uncomment the line below to enable it.
    #commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Hide the toggle button, along with the associated vertical divider
    hidecolorschemetoggle = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    customCSS = []

    # Custom SCSS
    customSCSS = []

    # Custom JS
    customJS = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/ismailhassani/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 3
    url = "https://twitter.com/ismailhassani/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/ismailhassani/"

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            #[[languages.en.menu.main]]
            #name = "About"
            #weight = 1
            #url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            #[[languages.en.menu.main]]
            #name = "Projects"
            #weight = 3
            #url = "projects/"

            #[[languages.en.menu.main]]
            #name = "Contact me"
            #weight = 5
            #url = "contact/"
